### ISSUE TITLE
What is the benefits over tsd?

### ISSUE THREAD

**Issue by gilamran** [vvakame/dtsm#14]
Can you share what are the benefits of dtsm over tsd?

**Comment by basarat** [comment]
Two major ones:

* Command line consistent with NPM : `dtsm angular --save` similarly `dtsm update --save` etc. 
* Uses `git clone` instead of github api. This means you can use bitbucket, private repos, local repos etc.


(cc @vvakame feel free to copy edit this message).

**Comment by rodrigovidal** [comment]
What about add these two major features to TSD? Is it impossible?

**Comment by basarat** [comment]
> Is it impossible?

No. But there is continued support needed for TSD. @diullei do you think if @vvakame wants we can migrate dtsm to be the new tsd? (v1?)

**Comment by rodrigovidal** [comment]
Again, why not just add these two features to the current TSD implementation? Is there a problem with the current implementation?

I'm really trying to understand what you want to achieve here.

**Comment by Diullei** [comment]
@basarat  after a long time away I'm backing with my open source contributions. This includes working more closely in the TSD and DefinitelyTyped projects. I think it makes more sense to add the mentioned features to TSD as @rodrigovidal said, rather than start over with a new project. I'm not shoot @vvakame's merit with dtsm looks like a really cool project, but I think we should not replace TSD. I know more support is needed, and I'm organizing myself to better understanding the work done by @bartvds to continue with the development of the TSD project. And of course, your contributions are welcome :)

**Comment by basarat** [comment]
Cool, Thanks for the clarification :rose: The two projects are significantly different and can continue their own separate paths for now :+1:

**Comment by Diullei** [comment]
:+1:

**Comment by vvakame** [comment]
I :heart: incremental search. ![](https://cloud.githubusercontent.com/assets/125332/5699331/88f612da-9a68-11e4-89c4-eaebaa4cb21b.gif)
check https://github.com/vvakame/dtsm#install-with-interactive-filtering

---

> Uses git clone instead of github api. This means you can use bitbucket, private repos, local repos etc.

now only support for `git://` and `http://`. not contains `file://`

---

>  @vvakame wants we can migrate dtsm to be the new tsd?

I don't want to do it. It occurred a trouble for existing users of tsd.

---

I'm did not get used to the code style of tsd and I want to get full control of development planning. 
I was create a new implementations in the end.
If you want to two features in tsd, I think you should open issues to tsd repo. :wink: 

---

@basarat @Diullei thanks friends!
